<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('todoist_tasks', function (Blueprint $table) {
            $table->comment('This table stores the respective ID of the task in the Todoist API.'
            . 'This ID is needed for the synchronization of the tasks between the application and the Todoist API.'
            . 'The "todoist_id" is unique and generated by Todoist services.');

            $table->id();
            $table->foreignId('task_id')->constrained();
            $table->bigInteger('todoist_id')->comment('ID of the task on the Todoist API.')->unique()->index();
            $table->timestamps();

            $table->unique(['task_id', 'todoist_id']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('todoist_tasks');
    }
};
